### ISSUE TITLE
Nested schema objects raise "schema missing"

### ISSUE THREAD

**Issue by baylee** [chaijs/chai-json-schema#37]
Hi, I'm trying to validate a complex schema. Some of my defined objects reference other defined objects, so there are nested references. Where these nested references are used, I get an error saying the schemas are missing. If I use a JSON schema validator, it confirms that my schema is valid.

Is there a way to have nested references?

Here is a simplified example:
```
{
    "properties": {
        "questions": { "$ref": "#/definitions/questions" }
    },
    "definitions": {
        "answers": {
            ...
            "id": "answers"
        },
        "questions": {
            "properties": {
                "answers": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/answers" }
                },
                ...
            },
            "id": "questions"
        }
    }
}
```
All the top level definitions (like `questions`) work fine. And if instead of a reference to `answers`, I just say `"type": "object"`, the error goes away.

**Comment by thabemmz** [comment]
Hi @baylee,

This is caused by using the `id` property in your definitions and is, generally speaking, only useful when you're working with loading schemas from a URL. See http://json-schema.org/latest/json-schema-core.html#anchor27 for more information.

About your example, as defined in the definition of JSON Schema:

> The "id" keyword (or "id", for short) is used to alter the resolution scope. When an id is encountered, an implementation MUST resolve this id against the most immediate parent scope. The resolved URI will be the new resolution scope for this subschema and all its children, until another id is encountered.

This means all nested properties within `#/definitions/questions` that use a `$ref` property are resolved as `questions#/definitions/answers` (`questions` being a schema identifier here). Since the `questions` schema isn't defined explicitly, this always errors.

The solution here is to remove the `id` property from your definitions as you probably don't need it. With the `id` fields removed this schema validates properly.

For more information about handling `id` fields, see [tv4](https://github.com/geraintluff/tv4) (we're using this internally for validation).
