### ISSUE TITLE
Not compatible with chai 4?

### ISSUE THREAD

**Issue by sverweij** [chaijs/chai-json-schema#47]
Hi @JrSchild - thanks for maintaining this chai plugin. It's very useful and should be a mandatory consideration for any project doing stuff with json and chai.

I've recently upped chai to version 4, and when installing chai-json-schema npm warns `The package chai@3.5.0 does not satisfy its siblings' peerDependencies requirements!` (see [travis jobs 99.1 - 99.3](https://travis-ci.org/chaijs/chai-json-schema) and the [PR greenkeeper made](https://github.com/chaijs/chai-json-schema/pull/46) to up chai). 

On npm versions < 3 (those distributed with node 4 and 0.x) this breaks any build using chai-json-schema. 

I've forked chai-json-schema, changed the `chai` peerDependencies range to `>= 1.6.1 < 5`, upped the `chai` dependency to 4.0.2 and ran the test suite => works OK.

1. Would you be willing to either make these changes or accept mine as a pull request?
2. In #26 I see there's some chores for this project that need doing. I'm willing to pick up some of these + the request @keithamus has for changing some build/ code quality tooling to chaijs guidelines. Would you be OK with that?

**Comment by keithamus** [comment]
A PR would be welcome IMO, but you should get a consensus from the rest of the @chaijs/chai-json-schema team

**Comment by JrSchild** [comment]
Hi @sverweij, I'm okay with you going ahead to fix the dependency versions. Feel free to create a PR.

Regarding the other items in the TODO list in issue #26. They're not really high priority because everything works well enough. We won't be spending too much time on it. However, should you feel inclined to help out, then those items could certainly use some attention.

**Comment by sverweij** [comment]
👍  see ☝️
